name: CI
on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install Dependencies
        run: npm ci

      - name: Check Code Formatting
        run: npm run format:Check

      - name: Run Automated Test
        run: npm test -- --coverage
        env:
          CI: true
      #- name: Upload Code Coverage as An Artifact
      #  run:
